### ISSUE TITLE
AutoSPInstallerConfigureRemoteTarget.ps1

### ISSUE THREAD

**Issue by hornickj** [brianlala/AutoSPInstaller#32]
C:\SP\Automation\AutoSPInstallerConfigureRemoteTarget.ps1 : The term
'C:\SP\Automation\AutoSPInstallerConfigureRemoteTarget.ps1' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:1
+ C:\SP\Automation\AutoSPInstallerConfigureRemoteTarget.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\SP\Automatio...emoteTarget.ps1:String) [], Comm
   andNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

powershell.exe exited on TESTWFE with error code 1.

**Comment by hornickj** [comment]
Sorry for not including more information related to it.

What I’m doing is dropping the custom XML file onto the .bat file and it starts the process, however the traditional SharePoint GUI dialog box pops up and wants the installation key along with confirming the directory locations.

A bigger issue I’m running into is the installation to remote systems within the XML file.
I’m able to run a PsExe remotely on this system, however it doesn’t seem to see the PowerShell script.  The error I’m seeing is the following:

- Server: TESTWFE
- Testing connection (via Ping) to "TESTWFE"...Success.
- Updating PowerShell execution policy on "TESTWFE" via PsExec...

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

powershell.exe exited on TESTWFE with error code -1.
- Enabling PowerShell remoting on "TESTWFE" via PsExec...

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com


C:\SP\Automation\AutoSPInstallerConfigureRemoteTarget.ps1 : The term
'C:\SP\Automation\AutoSPInstallerConfigureRemoteTarget.ps1' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:1
+ C:\SP\Automation\AutoSPInstallerConfigureRemoteTarget.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\SP\Automatio...emoteTarget.ps1:String) [], Comm
   andNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

powershell.exe exited on TESTWFE with error code 1.
- Starting remote session to TESTWFE...
New-PSSession : [TESTWFE] Connecting to remote server TESTWFE failed with the following error message : The WinRM
client cannot process the request. The authentication mechanism requested by the client is not supported by the server
or unencrypted traffic is disabled in the service configuration. Verify the unencrypted traffic setting in the service
configuration or specify one of the authentication mechanisms supported by the server.  To use Kerberos, specify the
computer name as the remote destination. Also verify that the client computer and the destination computer are joined
to a domain. To use Basic, specify the computer name as the remote destination, specify Basic authentication and
provide user name and password. Possible authentication mechanisms reported by server:     Negotiate Kerberos For more
information, see the about_Remote_Troubleshooting Help topic.
At C:\SP\Automation\AutoSPInstallerModule.psm1:6724 char:20
+ ...  $session = New-PSSession -Name "AutoSPInstallerSession-$server" -Aut ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotin
   gTransportException
    + FullyQualifiedErrorId : AccessDenied,PSSessionOpenFailed
--------------------------------------------------------------
- Script halted!

I really do appreciate how detailed the script is in the process.

Joey

**Comment by brianlala** [comment]
For the second issue, if you haven't manually copied all the required files (C:\SP\*.*) to each target SharePoint server, then the path C:\SP\Automation\AutoSPInstallerConfigureRemoteTarget.ps1 won't exist on other servers than the one you're running the script on. The best way to avoid this is to run the script from a UNC path like \\server1\c$\SP\Automation - this absolute path should be resolvable on all servers (assuming permissions are set correctly).

For the first issue, I have found that this is usually because there's an extra XML file located in the \Automation\ directory that's accidentally getting picked up by the script. Make sure only the XML file you're using as input (dragging onto the .bat) is present in that directory.

Hope this helps,
Brian

**Comment by hornickj** [comment]
Thank you for the quick response, I wasn’t sure if the script would copy the contents over or not.  I wasn’t able to find any commands referencing that process, but also didn’t want to make any assumption.

Joey

**Comment by hornickj** [comment]
Running it from a UNC path is a much better path so all systems are able to see the same files (and takes out human error.). I hope this is the final error/challenge I face:

From log file:
-----------------------------------
| Automated SP2016 Remote Installs |
| Started on: 12/21/2018 4:34:21 PM |
-----------------------------------
- Enabling WSManCredSSP for "TESTWFE"
- Enabling WSManCredSSP for "TESTCACHE"
- Enabling WSManCredSSP for "TESTWORKFLOW"
- Enabling WSManCredSSP for "TESTSEARCH"
--------------------------------------------------------------
- Server: TESTWFE
- Testing connection (via Ping) to "TESTWFE"...
Success.
- Updating PowerShell execution policy on "TESTWFE" via PsExec...
- Enabling PowerShell remoting on "TESTWFE" via PsExec...
- Starting remote session to TESTWFE...
- Starting remote session to TESTWFE...
- Starting remote session to TESTWFE...
PS>TerminatingError(): "Key cannot be null.
Parameter name: key"
>> TerminatingError(): "Key cannot be null.
Parameter name: key"
>> TerminatingError(): "Key cannot be null.
Parameter name: key"
--------------------------------------------------------------
- Script halted!

From PowerShell dialog:
Configuring PowerShell remoting...
WARNING: The updated configuration might affect the operation of the plugins having a per plugin
quota value greater than 1024. Verify the configuration of all the registered plugins and change
the per plugin quota values for the affected plugins.
powershell.exe exited on TESTWFE with error code -1.
- Starting remote session to TESTWFE...
- Starting remote session to TESTWFE...
- Starting remote session to TESTWFE...
--------------------------------------------------------------
- Script halted!


Exception             : System.ArgumentNullException: Key cannot be null.
                        Parameter name: key
                           at System.Collections.Hashtable.ContainsKey(Object key)
                           at System.Management.Automation.Language.PSGetDynamicMemberBinder.GetIDictionaryMember(IDict
                        ionary hash, Object key)
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1
                        arg1)
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
TargetObject          :
CategoryInfo          : OperationStopped: (:) [], ArgumentNullException
FullyQualifiedErrorId : System.ArgumentNullException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-MajorVersionNumber, \\staging\SP\Automation\AutoSPInstallerModule.psm1: line 7772
                        at Start-RemoteInstaller, \\staging\SP\Automation\AutoSPInstallerModule.psm1: line 6814
                        at Install-Remote, \\staging\SP\Automation\AutoSPInstallerMain.ps1: line 145
                        at <ScriptBlock>, \\staging\SP\Automation\AutoSPInstallerMain.ps1: line 433
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      :

**Comment by EckhardH** [comment]
I got exactly the same error. After some test I found out the the error was generated within the remote function "Start-remoteinstaller" by not getting the Version nummber. After commenting out line 7073 and 7074 in the AutoSPInstallerModule-File:
 # $spYear = $xmlInput.Configuration.Install.SPVersion
 # $spver = Get-MajorVersionNumber $spYear_
and hardcoding the correct version number into the variable:
 _$spVer ="16"_
the script started the remote installation in new PSSession Window correctly.
I have had some problems with the version nummber in earlier installations, too, and have been able to correct it this way. There seems to be a problem with reading the hashtable.
